# Generated by Django 4.0.8 on 2022-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0038_delete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='revbank_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
