# Generated by Django 4.0.8 on 2023-01-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LedenAdministratie", "0040_stripcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripcard",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripcards",
                to="LedenAdministratie.member",
            ),
        ),
    ]
