# Generated by Django 4.0.9 on 2023-02-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0041_alter_stripcard_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripcard',
            name='used',
            field=models.IntegerField(default=0, verbose_name='Gebruikt'),
        ),
    ]
