# Generated by Django 5.0.7 on 2024-08-07 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LedenAdministratie", "0043_member_ledenadmini_last_na_29bb48_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripcard",
            name="expiration_date",
            field=models.DateField(
                default=datetime.datetime(2099, 1, 1, 0, 0), verbose_name="Vervaldatum"
            ),
        ),
    ]
