# Generated by Django 5.1.7 on 2025-04-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LedenAdministratie", "0044_stripcard_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="media_toestemming",
            field=models.IntegerField(
                choices=[(1, "Toegestaan"), (2, "Onbekend"), (3, "Niet toegestaan")],
                default=2,
                verbose_name="Media toestemming",
            ),
        ),
    ]
