# Generated by Django 5.2.9 on 2025-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LedenAdministratie", "0045_member_media_toestemming"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
