# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 10:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=200)),
                ('gebdat', models.DateField(verbose_name=b'Geboorte Datum')),
                ('geslacht', models.CharField(choices=[(b'm', b'M'), (b'v', b'V')], default=b'm', max_length=1)),
                ('speltak', models.CharField(choices=[(b'wachtlijst', b'Wachtlijst'), (b'bevers', b'Bevers'), (b'welpen', b'Welpen'), (b'scouts', b'Scouts'), (b'explorers', b'Explorers'), (b'stam', b'Stam'), (b'leiding', b'Leiding'), (b'bestuur', b'Bestuur'), (b'oudleden', b'Oud-Leden')], default=b'wachtlijst', max_length=40)),
                ('email_address', models.EmailField(max_length=150, validators=[django.core.validators.EmailValidator(message=b'E-mail adres is ongeldig')])),
                ('straat', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message=b'De postcode is ongeldig', regex=b'\\d\\d\\d\\d\\s?[A-Za-z]{2}')])),
                ('woonplaats', models.CharField(max_length=100)),
                ('telnr', models.CharField(max_length=30)),
                ('mobiel', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message=b'Mobiel nummer is ongeldig', regex=b'06.*')])),
                ('mobiel_ouder1', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message=b'Mobiel nummer is ongeldig', regex=b'06.*')])),
                ('mobiel_ouder2', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message=b'Mobiel nummer is ongeldig', regex=b'06.*')])),
                ('email_ouder1', models.EmailField(blank=True, max_length=150)),
                ('email_ouder2', models.EmailField(blank=True, max_length=150)),
                ('aanmeld_datum', models.DateField(auto_now_add=True)),
                ('inschrijf_datum_sn', models.DateField(blank=True, null=True)),
                ('scouting_nr', models.CharField(blank=True, max_length=20)),
                ('tshirt_maat', models.CharField(blank=True, max_length=20)),
                ('jub_badge', models.CharField(blank=True, max_length=20)),
                ('verzekerings_nr', models.CharField(blank=True, max_length=20)),
                ('opmerkingen', models.TextField(blank=True, max_length=1024)),
                ('bijzonderheden', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name_plural': 'Leden',
            },
        ),
    ]
