# Generated by Django 2.1.5 on 2019-02-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now_add=True)),
                ('username', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='', max_length=65535)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LedenAdministratie.Member')),
            ],
        ),
    ]
