# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='email_address',
            field=models.EmailField(max_length=150, validators=[django.core.validators.EmailValidator(message='E-mail adres is ongeldig')]),
        ),
        migrations.AlterField(
            model_name='lid',
            name='gebdat',
            field=models.DateField(verbose_name='Geboorte Datum'),
        ),
        migrations.AlterField(
            model_name='lid',
            name='geslacht',
            field=models.CharField(choices=[('m', 'M'), ('v', 'V')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='lid',
            name='mobiel',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Mobiel nummer is ongeldig', regex='06.*')]),
        ),
        migrations.AlterField(
            model_name='lid',
            name='mobiel_ouder1',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Mobiel nummer is ongeldig', regex='06.*')]),
        ),
        migrations.AlterField(
            model_name='lid',
            name='mobiel_ouder2',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Mobiel nummer is ongeldig', regex='06.*')]),
        ),
        migrations.AlterField(
            model_name='lid',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='De postcode is ongeldig', regex='\\d\\d\\d\\d\\s?[A-Za-z]{2}')]),
        ),
        migrations.AlterField(
            model_name='lid',
            name='speltak',
            field=models.CharField(choices=[('wachtlijst', 'Wachtlijst'), ('bevers', 'Bevers'), ('welpen', 'Welpen'), ('scouts', 'Scouts'), ('explorers', 'Explorers'), ('stam', 'Stam'), ('leiding', 'Leiding'), ('bestuur', 'Bestuur'), ('oudleden', 'Oud-Leden')], default='wachtlijst', max_length=40),
        ),
    ]
