# Generated by Django 2.1.5 on 2019-02-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='datetime',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='note',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='LedenAdministratie.Member'),
        ),
    ]
