# Generated by Django 2.1.5 on 2019-02-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0003_auto_20190215_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='opmerkingen',
        ),
    ]
