# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0003_auto_20160930_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='speltak',
            field=models.CharField(choices=[('wachtlijst', 'Wachtlijst'), ('bevers', 'Bevers'), ('welpen', 'Welpen'), ('scouts', 'Scouts'), ('explorers', 'Explorers'), ('roverscouts', 'Roverscouts'), ('stam', 'Stam'), ('leiding', 'Leiding'), ('bestuur', 'Bestuur'), ('vrijwilliger', 'Vrijwilligers'), ('oudleden', 'Oud-Leden'), ('oudleiding', 'Oud-Leiding')], default='wachtlijst', max_length=40),
        ),
    ]
