# Generated by Django 2.1.5 on 2019-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0004_remove_member_opmerkingen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email_ouder1',
            new_name='email_ouders',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='mobiel_ouder1',
            new_name='mobiel_ouders',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email_ouder2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mobiel_ouder2',
        ),
    ]
