# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0004_auto_20161014_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='fotopubliek',
            field=models.BooleanField(default=False, verbose_name="Foto's publiceren toegestaan"),
        ),
    ]
