# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0005_lid_fotopubliek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lid',
            name='fotopubliek',
            field=models.BooleanField(default=True, verbose_name="Foto's publiceren toegestaan"),
        ),
    ]
