# Generated by Django 2.1.5 on 2019-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0006_auto_20190215_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telnr_ouders',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
