# Generated by Django 2.1.5 on 2019-02-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0007_auto_20190215_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('read_member', 'Can read members'),), 'verbose_name_plural': 'Leden'},
        ),
        migrations.AlterField(
            model_name='member',
            name='geslacht',
            field=models.CharField(choices=[('m', 'Man'), ('v', 'Vrouw'), ('o', 'Anders')], default='m', max_length=1),
        ),
    ]
