# Generated by Django 2.1.5 on 2019-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0008_auto_20190215_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dag_vrijdag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='dag_zaterdag',
            field=models.BooleanField(default=False),
        ),
    ]
