# Generated by Django 2.1.5 on 2019-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0009_auto_20190216_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='foto',
            field=models.BinaryField(null=True, verbose_name='Foto'),
        ),
    ]
