# Generated by Django 2.1.5 on 2019-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0010_member_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.BinaryField(editable=True, null=True, verbose_name='Foto'),
        ),
    ]
