# Generated by Django 2.1.5 on 2019-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0011_auto_20190217_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='foto',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Foto'),
        ),
    ]
