# Generated by Django 2.1.7 on 2019-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0015_auto_20190308_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='afmeld_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
