# Generated by Django 2.1.7 on 2019-03-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0016_member_afmeld_datum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Leden'},
        ),
    ]
