# Generated by Django 2.1.7 on 2019-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0017_auto_20190308_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='aanmeld_datum',
            field=models.DateField(auto_now_add=True, verbose_name='Aanmeld datum'),
        ),
    ]
