# Generated by Django 2.1.7 on 2019-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0018_auto_20190308_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='aanmeld_datum',
            field=models.DateField(verbose_name='Aanmeld datum'),
        ),
    ]
