# Generated by Django 2.1.7 on 2019-03-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0019_auto_20190308_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='afmeld_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Afmeld datum'),
        ),
    ]
