# Generated by Django 2.1.7 on 2019-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0020_auto_20190308_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hoe_gevonden',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
