# Generated by Django 2.1.7 on 2019-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0021_member_hoe_gevonden'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='smtp_error',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
