# Generated by Django 2.1.7 on 2019-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0023_auto_20190315_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Leden'},
        ),
        migrations.AddField(
            model_name='member',
            name='thumbnail',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Thumbnail'),
        ),
    ]
