# Generated by Django 2.1.7 on 2019-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0024_auto_20190329_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_ouders',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
