# Generated by Django 2.2.2 on 2019-06-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0028_auto_20190610_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.CharField(max_length=4096)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=4096)),
                ('sent_by', models.CharField(default='', max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='LedenAdministratie.Member')),
            ],
        ),
    ]
