# Generated by Django 2.2.2 on 2019-06-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0029_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='LedenAdministratie.Member'),
        ),
    ]
