# Generated by Django 2.2.2 on 2019-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0030_auto_20190610_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
