name: Run PR Tests

on:
  pull_request:
    branches:
      - djo

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint==3.2.6 pylint-django==2.5.5 black==24.8.0

      - name: Run pylint and black
        run: |
          black --check LedenAdministratie
          cp LedenAdministratie/settings.py.example LedenAdministratie/settings.py
          DJANGO_SETTINGS_MODULE="LedenAdministratie.settings" pylint --load-plugins=pylint_django LedenAdministratie
