name: Run PR Tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - djo

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint==4.0.6 pylint-django==2.8.0 black==26.5.1

      - name: Run pylint and black
        run: |
          black --check LedenAdministratie
          cp LedenAdministratie/settings.py.example LedenAdministratie/settings.py
          DJANGO_SETTINGS_MODULE="LedenAdministratie.settings" pylint --load-plugins=pylint_django LedenAdministratie
