name: Run PR Tests

on:
  pull_request:
    branches:
      - djo

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint==3.3.1 pylint-django==2.6.1 black==24.8.0

      - name: Run pylint and black
        run: |
          black --check LedenAdministratie
          cp LedenAdministratie/settings.py.example LedenAdministratie/settings.py
          DJANGO_SETTINGS_MODULE="LedenAdministratie.settings" pylint --load-plugins=pylint_django LedenAdministratie
